language: ruby
cache: bundler
rvm:
  - 2.0.0
env:
  - DB=postgresql
before_script:
  - cp config/database.ci.yml config/database.yml
  - psql -c 'create database formcraft_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
script:
  - bundle exec rspec